### PR TITLE
Change to make extension compatible with 10.x

### PR DESCRIPTION
**Pull request by garbast**
The core changed the way services and configuration are used. This should fix the extension to work with again.

### CODE REVIEW

**Comment by garbast** [comment]
In three and a half month this PR has it's first birthday.

**Comment by surphil** [comment]
Would be nice to have compatibilty to v10 +1

**Comment by infabo** [comment]
Open Source - just collaborate and improve. But there are always people - for whatever reason - don't give a shit. Not even a simple "hey garbast, thanks for your PR. We'll have a look into it when we have time. Thanks again!".

**Comment by zenobio93** [comment]
Won't be merged due same development in branch **10ltspoc** with some other modifications and bugfixes.

**Comment by infabo** [comment]
In 7 days this PR has his first birthday! He would have had at least. The opportunity to party & celebrate was taken from him. Poor PR. Now he's closed forever. :sob:

**Comment by garbast** [comment]
The 10ltspoc-composerupdate is stale since 13 month. So you are telling me, that a merge request with a BUGFIX cant make it into the extension, because a branch that is not worked on, blocks this?

And no, changes to README.md, composer.json and ext_emconf.php does not qualify as being worked on.

Having a look at the history makes me wonder, why i even think about submitting pull requests. It's is completly frustrating to get such results.

**Pull request closed without merging**
